# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-03 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('efinder_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='updated',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='url',
            new_name='register_url',
        ),
    ]
